### ISSUE TITLE
Social feed is broken

### ISSUE THREAD

**Issue by stacmi** [ASWWU-Web/atlas#4]
When visiting the aswwu website, the social feed for instagram is broken.

The error message is this:

```
Social

Failed to fetch instagram content.
```

**Comment by ermsdev** [comment]
waiting for information from Atlas

**Comment by ermsdev** [comment]
We need to get a new API key since the last one was presumably lost in the server failure last year. this should be pretty easy to get from instagram, but I didn't see it when I skimmed through the API documentation.
